PasteleriaBelen/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    #path('users/', include('users.urls')),
    path('services/', include('services.urls')),
    path('blog/', include('blog.urls')),
    path('page/', include('pages.urls')),
    path('contact/', include('contact.urls')),
    path('catalog/', include('catalog.urls')),
    path('admin/', admin.site.urls),
    #paths de Auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    #path de facturación
    path('billing/', include(('billing.urls', 'billing'), namespace="billing")),
]


#comprobamos si el debug está en marcha
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#Títulos para el administrador (configurando logo)
admin.site.site_header = 'Pastelería Belén'
admin.site.index_title = 'Panel de administrador'
admin.site.site_title = 'Pastelería Belén'

billing/urls.py
from django.urls import path
from billing.views import billList, billNew, billEdit

urlpatterns = [
    path('facturas/', billList.as_view(), name = "bill_list"),
    path('factura/new/', billNew.as_view(), name = "bill_new"),
    path('factura/edit/<int:pk>', billEdit.as_view(), name = "bill_edit"),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog, name="blog"),
    path('category/<int:category_id>/', views.category, name="category"),
]
#observación: el category_id, se pasará como parámetro auntomáticamente en la vista
#             recordar también, que ese parámetro siempre es cadena de caracteres, 
#             por eso lo casteamos a entero(int)

core/urls.py
from django.urls import path
from . import views
from .views import HomePageView, AboutPageView, StorePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('about/', AboutPageView.as_view(), name="about"),
    path('store/', StorePageView.as_view(), name="store"),
]

core/models.py
from django.db import models

# Creando un modelo abstracto
class ClaseModelo(models.Model):
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class HomePageView(TemplateView):
    template_name = "core/home.html"

class AboutPageView(TemplateView):
    template_name = "core/about.html"

class  StorePageView(TemplateView):
    template_name = "core/store.html"

core/templates/core/about.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Historia{% endblock %}

{% block content %}
<section class="page-section about-heading">
  <div class="container">
    <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="{% static 'core/img/about.jpg' %}" alt="">
    <div class="about-heading-content">
      <div class="row">
        <div class="col-xl-9 col-lg-10 mx-auto">
          <div class="bg-faded rounded p-5">
            <h2 class="section-heading mb-4">
              <span class="section-heading-upper">Tradición familiar</span>
              <span class="section-heading-lower">Nuestra historia</span>
            </h2>
            <p>Fundada en 2008. </p>
            <p>
            Pastelería Belen empezó en el 2008 en el distrito de San Juan Lurigancho como una aventura familiar, 
            impulsados por la iniciativa de nuestra madre. Comenzamos preparando todo tipo de tortas, 
            pasteles y bocaditos con nuestras mejores recetas caseras. Poco a poco gracias a la 
            publicidad boca a boca de nuestros amigos y allegados, comenzaron a llegar nuestros primeros 
            clientes, los cuales nos siguen acompañando. Así nos hicimos conocidos y empezamos a tener 
            una increíble y fiel clientela a quien le agradecemos de todo corazón.
            Los que nos motivan a seguir brindando lo mejor de nosotros, son Uds., nuestros clientes. 
            Queremos que cada celebración o antojo sea algo especial. En Pastelería Belen estamos orgullosos de 
            ser parte de ti, y nos hagan partícipes de sus momentos
            especiales.
            Nuestra intención siempre es ofrecerle lo mejor, con la calidad y frescura de siempre, 
            así como nuestras tortas, que aseguran ser la mejor elección para quedar bien ante los amigos,
            compañeros y familiares.
            Si tienes algún diseño o creación en mente, para alguna celebración especial, estamos a 
            tu entera disposición, con la misma atención personalizada y cálida de siempre en nuestros 
            2 locales.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %} | Belen</title>

    {% load static %}

    <!-- Bootstrap -->
    <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Fuentes -->
    <link href="{% static 'core/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">

    <!-- Estilos -->
    <link href="{% static 'core/css/business-casual.css' %}" rel="stylesheet">
    
    

  </head>

  <body>

    <h1 class="site-heading text-center text-white d-none d-lg-block">
      <span class="site-heading-upper text-primary mb-3">Auténtico Sabor</span>
      <span class="site-heading-lower">Pastelería Belen</span>
    </h1>

    <!-- Navegación -->
    <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
      <div class="container">
        <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url 'home' %}">Pastelería Belen</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item px-lg-4 {%if request.path == '/' %} active {%endif%}">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'home' %}">Inicio</a>
            </li>
            <li class="nav-item px-lg-4 {%if request.path == '/about/' %} active {%endif%}">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'about' %}">Historia</a>
            </li>
            <li class="nav-item px-lg-4 {%if request.path == '/services/' %} active {%endif%}">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'services' %}">Servicios</a>
            </li>
            <li class="nav-item px-lg-4 {%if request.path == '/store/' %} active {%endif%}">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'store' %}">Visítanos</a>
            </li>
            <li class="nav-item px-lg-4 {%if request.path == '/contact/' %} active {%endif%}">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'contact' %}">Contacto</a>
            </li>
            <li class="nav-item px-lg-4 {%if request.path|slice:":6" == '/blog/' %} active {%endif%}">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'blog' %}">Blog</a>
            </li>
          </ul>
          <ul class="navbar-nav mx-auto">
            
            {% if not request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Acceder</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'signup' %}">Registro</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'profile' %}">Perfil</a>
              </li>
              {% if request.user.is_staff %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'billing:bill_list' %}">Facturación</a>
                </li>
              {% endif %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">Salir</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    {% block content %} {% endblock %}

    <!-- Pié de página -->
    <footer class="footer text-faded text-center py-3 m-0">
      <div class="container text-center">
        <p class="m-0">
          {% if LINK_TWITTER %}
            <a href="{{LINK_TWITTER}}" class="link">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          {% endif %}
          {% if LINK_FACEBOOK %}
            <a href="{{LINK_FACEBOOK}}" class="link">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          {% endif %}
          {% if LINK_INSTAGRAM %}
            <a href="LINK_INSTAGRAM" class="link">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          {% endif %}
	      </p>
        <!-- <p class="m-0 mbt">
          {% load pages_extras %}
          {% get_page_list as page_list %}
          {% for page in page_list %}
          <a href="{% url 'page' page.id %}" class="link">{{page.title}}</a> {%if not forloop.last%}·{%endif%}
          {% endfor %} -->
        <!--	<a href="sample.html" class="link">Política de privacidad</a> ·
        	<a href="sample.html" class="link">Aviso legal</a> ·
        	<a href="sample.html" class="link">Cookies</a> -->
		    <!-- </p> -->
        <p class="m-0 mtb1">&copy; Pastelería Belén 2020</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>

core/templates/core/base_fact.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
        {% block head_title %}
            Facturación
        {% endblock head_title %}
    </title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static 'core/css/metisMenu.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'core/css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'core/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Principal</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> {{ user.username }} <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Salir</a>
                    </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="#"><i class="fa fa-inbox fa-fw"></i> Ventas <span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'billing:bill_list' %}">Facturación</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <small class="text-danger">
                    {% if form.errors %}
                    {% for field in form %}
                    {% if field.errors %}
                    {% for error in field.errors %}
                    {{ error|escape }}
                    {% endfor %}
                    {% endif %}
                    {% endfor %}
                    {% if form.non_field_errors%}
                    {% for error in form.non_field_errors %}
                    {{ error|escape }}
                    {% endfor %}
                    {% endif %}
                    {% endif %}
                </small>
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            <small class="text-danger text-center">
                                {% if messages %}
                                {% for message in messages %}
                                {{ message|safe }}<br>
                                {% endfor %}
                                {% endif %}
                            </small>
                        </h1>
                        {% block contenido %}Blank{% endblock contenido %}
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="{% static 'core/js/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'core/js/bootstrap.min.js' %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'core/js/metisMenu.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'core/js/sb-admin-2.js' %}"></script>

</body>

</html>

core/templates/core/home.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Inicio{% endblock %}

{% block content %}

<!-- Cabecera -->
<section class="page-section clearfix">
  <div class="container">
    <div class="intro">
      <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'core/img/intro.jpg' %}" alt="">
      <div class="intro-text left-0 text-center bg-faded p-5 rounded">
        <h2 class="section-heading mb-4">
          <span class="section-heading-upper">Déjate sorprender</span>
          <span class="section-heading-lower">Te gustará</span>
        </h2>
        <p class="mb-3">Trabajamos sólo con los mejores ingredientes. Una vez pruebes nuestros productos, serán la mejor forma de empezar tu rutina semamal.
        </p>
        <div class="intro-button mx-auto">
          <a class="btn btn-primary btn-xl" href="{% url 'store' %}">Visítanos</a>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Mensaje -->
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="cta-inner text-center rounded">
          <h2 class="section-heading mb-4">
            <span class="section-heading-upper">Compromiso total</span>
            <span class="section-heading-lower">Garantizado</span>
          </h2>
          <p class="mb-0">Contamos con todos los registros de calidad posibles, para garantizar los mejores productos para usted y su familia.</p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

core/templates/core/store.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Visítanos{% endblock %}

{% block content %}
<section class="page-section cta">
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="cta-inner text-center rounded">
          <h2 class="section-heading mb-5">
            <span class="section-heading-upper">Te esperamos</span>
            <span class="section-heading-lower">Visítanos</span>
          </h2>
          <ul class="list-unstyled list-hours mb-5 text-left mx-auto">
            <li class="list-unstyled-item list-hours-item d-flex">
              Lunes a viernes
              <span class="ml-auto">7:00 a 22:00</span>
            </li>
            <li class="list-unstyled-item list-hours-item d-flex">
              Sábados
              <span class="ml-auto">7:00 a 17:00</span>
            </li>
            <li class="list-unstyled-item list-hours-item d-flex">
              Domingos
              <span class="ml-auto">7:00 a 12:00</span>
            </li>
          </ul>
          <p class="address mb-5">
            <em>
              <strong>Ave. Canto Grande nº 555</strong>
              <br>
              Lima
            </em>
          </p>
          <p class="mb-0">
            <small>
              <em>Llámanos y pregunta</em>
            </small>
            <br>
            (051) 555-5555
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}