PasteleriaBelen/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    #path('users/', include('users.urls')),
    path('services/', include('services.urls')),
    path('blog/', include('blog.urls')),
    path('page/', include('pages.urls')),
    path('contact/', include('contact.urls')),
    path('catalog/', include('catalog.urls')),
    path('admin/', admin.site.urls),
    #paths de Auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    #path de facturación
    path('billing/', include(('billing.urls', 'billing'), namespace="billing")),
]


#comprobamos si el debug está en marcha
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#Títulos para el administrador (configurando logo)
admin.site.site_header = 'Pastelería Belén'
admin.site.index_title = 'Panel de administrador'
admin.site.site_title = 'Pastelería Belén'

billing/urls.py
from django.urls import path
from billing.views import billList, billNew, billEdit

urlpatterns = [
    path('facturas/', billList.as_view(), name = "bill_list"),
    path('factura/new/', billNew.as_view(), name = "bill_new"),
    path('factura/edit/<int:pk>', billEdit.as_view(), name = "bill_edit"),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog, name="blog"),
    path('category/<int:category_id>/', views.category, name="category"),
]
#observación: el category_id, se pasará como parámetro auntomáticamente en la vista
#             recordar también, que ese parámetro siempre es cadena de caracteres, 
#             por eso lo casteamos a entero(int)

billing/models.py
from django.db import models
from core.models import ClaseModelo
from catalog.models import design
from decimal import Decimal

# Creando modelos de maestro detalle

class bill(ClaseModelo): #factura
    date_bill = models.DateField()
    observation = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.date_bill)

    class Meta:
        verbose_name = "Factura"
        verbose_name_plural = "Facturas"

class billDetail(ClaseModelo): #detalle factura
    bill = models.ForeignKey(bill, on_delete=models.CASCADE)
    design = models.ForeignKey(design, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=6, decimal_places=2, blank=False, null=False, default=0)
    total = models.DecimalField(max_digits=6, decimal_places=2, default=0)

    def __str__(self):
        return '{} - {}'.format(self.bill, self.design)
    
    def save(self):
        self.total = Decimal(self.cantidad) * Decimal(self.price)
        super(billDetail, self).save()

    class Meta:
        verbose_name = "Detalle de Factura"
        verbose_name_plural = "Detalles de Facturas"

billing/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from billing.models import bill, billDetail
from catalog.models import design

class billForm(forms.ModelForm):
    date_bill = forms.DateInput()

    class Meta:
        model = bill
        fields = ['date_bill', 'observation']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class' : 'form-control'
            })

class billDetailForm(forms.ModelForm):
    design = forms.ModelChoiceField(
        queryset=design.objects.filter(activo=True).
        order_by("description"),
        empty_label="Seleccione Producto"
    )

    class Meta:
        model = billDetail
        fields = ['design', 'cantidad', 'price', 'total']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        self.fields['total'].widget.attrs['readonly'] = True
    
    #si sucede algo se queda en el error, sino devuelve la cantidad
    def clean_cantidad(self):
        cantidad = self.cleaned_data['cantidad']
        if not cantidad:
            raise forms.ValidationError("Cantidad Requerida")
        elif cantidad <= 0:
            raise forms.ValidationError("Cantidad Incorrecta")
        return cantidad
    
    def clean_price(self):
        price = self.cleaned_data['price']
        if not price:
            raise forms.ValidationError("Precio Requerido")
        elif price <= 0:
            raise forms.ValidationError("Precio Incorrecto")
        return price

#Vinculamos los dos modelos de factura y detalles a un formulario
DetailBillFormSet = inlineformset_factory(bill, billDetail, form=billDetailForm, extra=4)

billing/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView
from .models import bill, billDetail
from .forms import billForm, billDetailForm, DetailBillFormSet

# Creando lista de facturas
class billList(LoginRequiredMixin, ListView):
    login_url = 'login'
    model = bill
    template_name = "billing/bill_list.html"
    context_object_name = "facturas"

class billNew(PermissionRequiredMixin, CreateView):
    permission_required = 'billing.add_bill'
    model = bill
    login_url = 'core:home'
    template_name = 'billing/bill_form.html'
    form_class = billForm
    success_url = reverse_lazy('billing:bill_list')

    #cargar formulario vacío cuando se ejecute la vista
    def get(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class() #reconocemos factura
        form = self.get_form(form_class) #cargamos los datos de la factura en form
        detalle_bill_formset = DetailBillFormSet() #instanciamos detalles
        return self.render_to_response(self.get_context_data(
            form = form,
            detail_bill = detalle_bill_formset
        ))
    
    #sobreescribiendo método post
    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        detail_bill = DetailBillFormSet(request.POST) #obtener datos con lo que se pasó en el post

        #validando los datos de la factura y de los detalles
        if form.is_valid() and detail_bill.is_valid():
            return self.form_valid(form, detail_bill)
        else:
            return self.form_invalid(form, detail_bill)
    
    #personalizamos los métodos de validación
    def form_valid(self, form, detail_bill):
        self.object = form.save() #guardamos la factura
        detail_bill.instance = self.object #cargamos una instancia del conjunto de detalles vinculados a la factura
        detail_bill.save() #guardamos esa instancia
        return HttpResponseRedirect(self.success_url)
    
    def form_invalid(self, form, detail_bill):
        return self.render_to_response(
            #lo regresamos a como estaba con los datos del formulario antes de que haga el envío
            self.get_context_data(
                form = form,
                detail_bill = detail_bill
            )
        )



class billEdit(PermissionRequiredMixin, UpdateView):
    permission_required = 'billing.change_bill'
    model = bill
    login_url = 'core:home'
    template_name = 'billing/bill_form.html'
    form_class = billForm
    success_url = reverse_lazy('billing:bill_list')

    def get_success_url(self):
        from django.urls import reverse
        #redireccionamos el success_url
        return reverse('billing:bill_edit', kwargs={'pk':self.get_object().id})
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        detail = billDetail.objects.filter(bill=self.object).order_by('pk')
        detail_data = []
        for det in detail:
            d = {
                'design':det.design,
                'cantidad':det.cantidad,
                'price':det.price,
                'total':det.total
            }
            detail_data.append(d)
        
        detail_bill = DetailBillFormSet(initial=detail_data)
        detail_bill.extra += len(detail_data)
        return self.render_to_response(self.get_context_data(
            form = form,
            detail_bill = detail_bill
        ))
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        detail_bill = DetailBillFormSet(request.POST)
        if form.is_valid() and detail_bill.is_valid():
            return self.form_valid(form, detail_bill)
        else:
            return self.form_invalid(form, detail_bill)
    
    def form_valid(self, form, detail_bill):
        self.object = form.save()
        detail_bill.instance = self.object
        billDetail.objects.filter(bill=self.object).delete()
        detail_bill.save()
        return HttpResponseRedirect(self.get_success_url())
    
    def form_invalid(self, form, detail_bill):
        return self.render_to_response(
            #lo regresamos a como estaba con los datos del formulario antes de que haga el envío
            self.get_context_data(
                form = form,
                detail_bill = detail_bill
            )
        )

billing/templates/billing/bill_form.html
{% extends 'core/base_fact.html' %}
{% block contenido%}
{% if form.errors %}
    {% for field in form %}
        {% if field.errors %}
            <div class="alert alert-danger fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {% for error in field.errors %}
                    <strong>{{ error|escape }}</strong>
            {% endfor %}
            </div>
        {% endif %} 
    {% endfor %}
    {% if form.non_field_errors%}
        <div class="alert alert-danger">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {% for error in form.non_field_errors %}
            
                <strong>{{ error|escape }}</strong>
        {% endfor %}
        </div>
    {% endif %}
{% endif %}

{% if object %}
<form method="POST" action="{% url 'billing:bill_edit' object.pk %}">
{% else %}
<form method="POST" action="{% url 'billing:bill_new' %}">
{% endif %}
    <div class="panel panel-red">
        <div class="panel-heading">
            {% if object %} Editar {% else %} Nueva {% endif %} Factura
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
                {% csrf_token %}
                <div class="col-md-6">
                    <div class="form-group has-success">
                        <label class="control-label" for="inputSuccess">Fecha</label>
                        {{ form.date_bill }}
                        <small class="text-danger">{{form.errors.date_bill}}</small>
                        {% if form.date_bill.errors %}
                            {% for error in form.date_bill.errors %}
                                <small class="text-danger">{{ error|escape }} </small>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group has-success">
                        <label class="control-label" for="inputSuccess">Observaciones</label>
                        {{ form.observation }}
                        <small class="text-danger">{{form.errors.observation}}</small>
                    </div>
                </div> 
                {{ detail_bill.management_form }}
                <table class="table">
                    <thead>
                        <td class="text-center">Producto</td>
                        <td class="text-center">Cantidad</td>
                        <td class="text-center">Precio</td>
                        <td class="text-center">Total</td>
                        <td class="text-center">Borrar</td>
                    </thead>
                    <tbody>
                        {% for detalle in detail_bill %}
                        <tr>
                            <td>{{ detalle.design }}</td>
                            <td> {{ detalle.cantidad }}
                                {% if detalle.cantidad.errors %}
                                    {% for error in detalle.cantidad.errors %}
                                        <small class="text-danger">{{ error|escape }} </small>
                                    {% endfor %}
                                {% endif %}
                            </td>
                            <td>
                                {{ detalle.price }}
                                {% if detalle.price.errors %}
                                    {% for error in detalle.price.errors %}
                                        <small class="text-danger">{{ error|escape }} </small>
                                    {% endfor %}
                                {% endif %}
                            </td>
                            <td> {{ detalle.total }} </td>
                            <td>{{  detalle.DELETE }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
        </div>
        <div class="panel-footer">
            <div class="text-center">
                <button type="submit" class="btn btn-social-icon btn-danger" name="submit"><i class="fa fa-save"></i> Guardar</button>
                <a class="btn btn-social-icon btn-warning" href="{% url 'billing:bill_list' %}"><i class="fa fa-times"></i> Cancelar</a>
            </div>
        </div>
    </div>
</form>
{% endblock contenido%}

billing/templates/billing/bill_list.html
{% extends "core/base_fact.html" %}
{% block contenido %}
<div class="panel panel-default">
    <div class="panel-heading">
        <a href="{% url 'billing:bill_new' %}" class="btn btn-info"><span class="fa fa-plus-circle"></span> Nueva Factura</a>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
                <tr>
                    <th>No. Fact</th>
                    <th>Fecha Fact.</th>
                    <th>Observacion</th>
                    <th>Creado</th>
                    <th>Modificado</th>
                    <th class="all">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for item in facturas %}
                <tr>
                    <td>{{item.id}}</td>
                    <td>{{item.date_bill|date:'d/m/Y'}}</td>
                    <td>{{item.observation}}</td>
                    <td>{{item.creado|date:'d/m/Y H:i'}}</td>
                    <td>{{item.modificado|date:'d/m/Y H:i'}}</td>
                    <td>
                        <a href="{% url 'billing:bill_edit' item.id %}" class="btn btn-primary btn-circle">
                            <span class="fa fa-edit"></span>
                        </a>
                    </td>
                </tr>
                {% endfor%}
            </tbody>
        </table>
    </div>
</div>
{% endblock contenido%}